In [1]:
import numpy as np

x = np.array([1,2,3]) 
print("x: \n{}".format(x))

x = np.array([[1, 2], [3, 4]]) 
print("x new : \n{}".format(x))

x = np.array([1, 2, 3,4,5], ndmin = 2) 
print("x with min dimension: \n{}".format(x))

x = np.array([1, 2, 3], dtype = complex)
print("x with dtype: \n{}".format(x))



x: 
[1 2 3]
x new : 
[[1 2]
 [3 4]]
x with min dimension: 
[[1 2 3 4 5]]
x with dtype: 
[1.+0.j 2.+0.j 3.+0.j]
